import type {
  NewsArticle,
  NarrativeCluster,
  Reporter,
  InvestmentSignal,
  MarketTicker,
} from "@/types";

export const mockArticles: NewsArticle[] = [
  {
    id: "a1",
    title: "Federal Reserve signals potential rate cuts amid economic uncertainty",
    titleOriginal: "Federal Reserve signals potential rate cuts amid economic uncertainty",
    source: "The Wall Street Journal",
    country: "United States",
    countryCode: "US",
    language: "English",
    flag: "🇺🇸",
    timestamp: new Date(Date.now() - 12 * 60 * 1000),
    sentiment: "neutral",
    sentimentScore: 0.2,
    category: "Economy",
    clusterId: "c1",
    reporter: "Sarah Mitchell",
    reporterBiasScore: 84,
    url: "#",
    summary: "The Federal Reserve hinted at possible interest rate reductions as inflation indicators show mixed signals across various sectors of the American economy.",
  },
  {
    id: "a2",
    title: "米連邦準備制度、経済不確実性の中で利下げの可能性を示唆",
    titleOriginal: "米連邦準備制度、経済不確実性の中で利下げの可能性を示唆",
    source: "日本経済新聞",
    country: "Japan",
    countryCode: "JP",
    language: "Japanese",
    flag: "🇯🇵",
    timestamp: new Date(Date.now() - 18 * 60 * 1000),
    sentiment: "positive",
    sentimentScore: 0.6,
    category: "Economy",
    clusterId: "c1",
    reporter: "Tanaka Hiroshi",
    reporterBiasScore: 91,
    url: "#",
    summary: "The Federal Reserve may ease monetary policy, which analysts predict will benefit Asian export markets and boost the Nikkei in the near term.",
  },
  {
    id: "a3",
    title: "US-Notenbank signalisiert mögliche Zinssenkungen",
    titleOriginal: "US-Notenbank signalisiert mögliche Zinssenkungen",
    source: "Frankfurter Allgemeine Zeitung",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    flag: "🇩🇪",
    timestamp: new Date(Date.now() - 25 * 60 * 1000),
    sentiment: "positive",
    sentimentScore: 0.55,
    category: "Economy",
    clusterId: "c1",
    reporter: "Klaus Weber",
    reporterBiasScore: 88,
    url: "#",
    summary: "Rate cuts by the Fed could strengthen European exports and relieve pressure on the ECB, according to Frankfurt economists.",
  },
  {
    id: "a4",
    title: "China's technology sector surges as domestic AI investments accelerate",
    titleOriginal: "中国科技行业因国内人工智能投资加速而飙升",
    source: "Global Times",
    country: "China",
    countryCode: "CN",
    language: "Chinese",
    flag: "🇨🇳",
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    sentiment: "positive",
    sentimentScore: 0.85,
    category: "Technology",
    clusterId: "c2",
    reporter: "Li Wei",
    reporterBiasScore: 52,
    url: "#",
    summary: "Chinese tech giants are seeing record highs as the government doubles down on domestic AI semiconductor production and model training.",
  },
  {
    id: "a5",
    title: "Sector tecnológico de China amenaza la hegemonía occidental de IA",
    titleOriginal: "Sector tecnológico de China amenaza la hegemonía occidental de IA",
    source: "El País",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    flag: "🇪🇸",
    timestamp: new Date(Date.now() - 32 * 60 * 1000),
    sentiment: "negative",
    sentimentScore: -0.4,
    category: "Technology",
    clusterId: "c2",
    reporter: "Carlos Mendez",
    reporterBiasScore: 76,
    url: "#",
    summary: "European analysts warn that rapid Chinese AI advancement could undermine Western dominance in key technology sectors by 2027.",
  },
  {
    id: "a6",
    title: "भारत में नवीकरणीय ऊर्जा में रिकॉर्ड निवेश",
    titleOriginal: "भारत में नवीकरणीय ऊर्जा में रिकॉर्ड निवेश",
    source: "The Hindu",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    flag: "🇮🇳",
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    sentiment: "positive",
    sentimentScore: 0.75,
    category: "Energy",
    clusterId: "c3",
    reporter: "Priya Sharma",
    reporterBiasScore: 82,
    url: "#",
    summary: "India sets a new record for renewable energy investment, with solar and wind projects attracting over $28B in foreign direct investment this quarter.",
  },
  {
    id: "a7",
    title: "Investimentos recordes em energia renovável na Índia atraem interesse brasileiro",
    titleOriginal: "Investimentos recordes em energia renovável na Índia atraem interesse brasileiro",
    source: "Folha de S.Paulo",
    country: "Brazil",
    countryCode: "BR",
    language: "Portuguese",
    flag: "🇧🇷",
    timestamp: new Date(Date.now() - 55 * 60 * 1000),
    sentiment: "positive",
    sentimentScore: 0.68,
    category: "Energy",
    clusterId: "c3",
    reporter: "Ana Costa",
    reporterBiasScore: 79,
    url: "#",
    summary: "Brazil looks to replicate India's renewable energy model as both nations explore South-South cooperation on clean energy infrastructure.",
  },
  {
    id: "a8",
    title: "Investissement record en énergie renouvelable en Afrique subsaharienne",
    titleOriginal: "Investissement record en énergie renouvelable en Afrique subsaharienne",
    source: "Le Monde Afrique",
    country: "Senegal",
    countryCode: "SN",
    language: "French",
    flag: "🇸🇳",
    timestamp: new Date(Date.now() - 65 * 60 * 1000),
    sentiment: "positive",
    sentimentScore: 0.72,
    category: "Energy",
    clusterId: "c3",
    reporter: "Fatou Diallo",
    reporterBiasScore: 85,
    url: "#",
    summary: "Sub-Saharan Africa is experiencing a renewable energy boom with record foreign investments flowing into solar micro-grids and wind farms.",
  },
  {
    id: "a9",
    title: "Напряженность между Россией и НАТО достигла нового максимума",
    titleOriginal: "Напряженность между Россией и НАТО достигла нового максимума",
    source: "РИА Новости",
    country: "Russia",
    countryCode: "RU",
    language: "Russian",
    flag: "🇷🇺",
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
    sentiment: "negative",
    sentimentScore: -0.7,
    category: "Geopolitics",
    clusterId: "c4",
    reporter: "Ivan Petrov",
    reporterBiasScore: 31,
    url: "#",
    summary: "Russian state media reports NATO military exercises near borders as provocative, calling for immediate de-escalation of Western aggression.",
  },
  {
    id: "a10",
    title: "NATO strengthens eastern flank amid continued Russian provocations",
    titleOriginal: "NATO strengthens eastern flank amid continued Russian provocations",
    source: "The Guardian",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    flag: "🇬🇧",
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    sentiment: "negative",
    sentimentScore: -0.55,
    category: "Geopolitics",
    clusterId: "c4",
    reporter: "James Thompson",
    reporterBiasScore: 71,
    url: "#",
    summary: "NATO allies are bolstering defenses along the eastern European flank in response to escalating Russian military activity.",
  },
  {
    id: "a11",
    title: "تحقيق تاريخي في اتفاقية السلام بالشرق الأوسط",
    titleOriginal: "تحقيق تاريخي في اتفاقية السلام بالشرق الأوسط",
    source: "Al Jazeera",
    country: "Qatar",
    countryCode: "QA",
    language: "Arabic",
    flag: "🇶🇦",
    timestamp: new Date(Date.now() - 22 * 60 * 1000),
    sentiment: "positive",
    sentimentScore: 0.45,
    category: "Geopolitics",
    clusterId: "c4",
    reporter: "Mohammed Al-Rashid",
    reporterBiasScore: 67,
    url: "#",
    summary: "Diplomatic sources indicate preliminary agreements on a Middle East peace framework are gaining momentum with quiet backing from Gulf states.",
  },
  {
    id: "a12",
    title: "글로벌 반도체 부족 사태 완화 조짐",
    titleOriginal: "글로벌 반도체 부족 사태 완화 조짐",
    source: "조선일보",
    country: "South Korea",
    countryCode: "KR",
    language: "Korean",
    flag: "🇰🇷",
    timestamp: new Date(Date.now() - 40 * 60 * 1000),
    sentiment: "positive",
    sentimentScore: 0.62,
    category: "Technology",
    clusterId: "c2",
    reporter: "Kim Ji-yeon",
    reporterBiasScore: 88,
    url: "#",
    summary: "Samsung and SK Hynix report production normalization, suggesting the global semiconductor shortage may ease significantly in the next two quarters.",
  },
  {
    id: "a13",
    title: "Carenza di chip: la Corea del Sud guida la ripresa",
    titleOriginal: "Carenza di chip: la Corea del Sud guida la ripresa",
    source: "Corriere della Sera",
    country: "Italy",
    countryCode: "IT",
    language: "Italian",
    flag: "🇮🇹",
    timestamp: new Date(Date.now() - 50 * 60 * 1000),
    sentiment: "positive",
    sentimentScore: 0.58,
    category: "Technology",
    clusterId: "c2",
    reporter: "Marco Ferrari",
    reporterBiasScore: 81,
    url: "#",
    summary: "Italian manufacturing sectors are cautiously optimistic as Korean chipmakers signal recovery, potentially ending supply chain bottlenecks.",
  },
  {
    id: "a14",
    title: "Crise climatique: record de températures en Australie",
    titleOriginal: "Crise climatique: record de températures en Australie",
    source: "Le Monde",
    country: "France",
    countryCode: "FR",
    language: "French",
    flag: "🇫🇷",
    timestamp: new Date(Date.now() - 70 * 60 * 1000),
    sentiment: "negative",
    sentimentScore: -0.65,
    category: "Climate",
    clusterId: "c5",
    reporter: "Marie Dupont",
    reporterBiasScore: 86,
    url: "#",
    summary: "Australia records its hottest summer on record, with scientists warning of accelerating climate tipping points that could affect global food production.",
  },
  {
    id: "a15",
    title: "Récord de temperatura en el hemisferio sur preocupa a científicos latinoamericanos",
    titleOriginal: "Récord de temperatura en el hemisferio sur preocupa a científicos latinoamericanos",
    source: "La Nación",
    country: "Argentina",
    countryCode: "AR",
    language: "Spanish",
    flag: "🇦🇷",
    timestamp: new Date(Date.now() - 80 * 60 * 1000),
    sentiment: "negative",
    sentimentScore: -0.7,
    category: "Climate",
    clusterId: "c5",
    reporter: "Diego Morales",
    reporterBiasScore: 83,
    url: "#",
    summary: "Latin American climate scientists warn that record Southern Hemisphere temperatures signal irreversible agricultural disruptions for 2026-2027.",
  },
];

export const mockClusters: NarrativeCluster[] = [
  {
    id: "c1",
    label: "Fed Rate Policy",
    countries: ["United States", "Japan", "Germany", "Australia", "Canada"],
    flags: ["🇺🇸", "🇯🇵", "🇩🇪", "🇦🇺", "🇨🇦"],
    narrative: "Western economies anticipate a Fed pivot in H2 2024, with markets pricing in 2-3 rate cuts. Asian and European outlets are broadly optimistic about the potential easing effects on their export markets.",
    sentiment: 0.52,
    articleCount: 47,
    divergence: 18,
    color: "#3b82f6",
  },
  {
    id: "c2",
    label: "AI & Chip Wars",
    countries: ["China", "South Korea", "Taiwan", "United States", "Spain", "Italy"],
    flags: ["🇨🇳", "🇰🇷", "🇹🇼", "🇺🇸", "🇪🇸", "🇮🇹"],
    narrative: "Strong divergence: Chinese and Korean outlets frame AI advancement as domestic triumph and economic opportunity, while Western European media emphasizes geopolitical risk and supply chain dependency.",
    sentiment: 0.21,
    articleCount: 63,
    divergence: 74,
    color: "#8b5cf6",
  },
  {
    id: "c3",
    label: "Clean Energy Boom",
    countries: ["India", "Brazil", "Senegal", "Indonesia", "Vietnam"],
    flags: ["🇮🇳", "🇧🇷", "🇸🇳", "🇮🇩", "🇻🇳"],
    narrative: "Exclusive Global South cluster: Nations outside the G7 are collectively reporting an unprecedented wave of renewable investment, largely undercovered by Western media. Potential emerging market opportunity.",
    sentiment: 0.71,
    articleCount: 38,
    divergence: 12,
    color: "#10b981",
  },
  {
    id: "c4",
    label: "Geopolitical Tensions",
    countries: ["Russia", "United Kingdom", "Qatar", "Poland", "Turkey"],
    flags: ["🇷🇺", "🇬🇧", "🇶🇦", "🇵🇱", "🇹🇷"],
    narrative: "Maximum divergence detected: Russian and Western outlets present completely opposite narratives on the same events. Middle Eastern outlets (Qatar, Turkey) provide a third, more diplomatic framing.",
    sentiment: -0.48,
    articleCount: 89,
    divergence: 96,
    color: "#ef4444",
  },
  {
    id: "c5",
    label: "Climate Records",
    countries: ["France", "Argentina", "Australia", "Bangladesh", "Kenya"],
    flags: ["🇫🇷", "🇦🇷", "🇦🇺", "🇧🇩", "🇰🇪"],
    narrative: "High consensus across disparate regions: European, South American, and African outlets are reporting increasingly alarming climate metrics. Rare case of global narrative convergence on urgency.",
    sentiment: -0.65,
    articleCount: 52,
    divergence: 8,
    color: "#f59e0b",
  },
];

export const mockReporters: Reporter[] = [
  {
    id: "r1",
    name: "Tanaka Hiroshi",
    outlet: "日本経済新聞",
    country: "Japan",
    flag: "🇯🇵",
    neutralityScore: 91,
    biasDirection: "neutral",
    articleCount: 847,
    topics: ["Economy", "Finance", "Trade"],
    trend: "stable",
  },
  {
    id: "r2",
    name: "Sarah Mitchell",
    outlet: "Wall Street Journal",
    country: "United States",
    flag: "🇺🇸",
    neutralityScore: 84,
    biasDirection: "neutral",
    articleCount: 1203,
    topics: ["Markets", "Fed Policy", "Banking"],
    trend: "improving",
  },
  {
    id: "r3",
    name: "Fatou Diallo",
    outlet: "Le Monde Afrique",
    country: "Senegal",
    flag: "🇸🇳",
    neutralityScore: 85,
    biasDirection: "neutral",
    articleCount: 412,
    topics: ["Energy", "Development", "Climate"],
    trend: "improving",
  },
  {
    id: "r4",
    name: "Klaus Weber",
    outlet: "Frankfurter Allgemeine",
    country: "Germany",
    flag: "🇩🇪",
    neutralityScore: 88,
    biasDirection: "neutral",
    articleCount: 678,
    topics: ["EU Policy", "Economy", "Trade"],
    trend: "stable",
  },
  {
    id: "r5",
    name: "Carlos Mendez",
    outlet: "El País",
    country: "Spain",
    flag: "🇪🇸",
    neutralityScore: 76,
    biasDirection: "left",
    articleCount: 534,
    topics: ["Technology", "Geopolitics", "EU"],
    trend: "declining",
  },
  {
    id: "r6",
    name: "Li Wei",
    outlet: "Global Times",
    country: "China",
    flag: "🇨🇳",
    neutralityScore: 52,
    biasDirection: "right",
    articleCount: 2341,
    topics: ["Technology", "Trade", "Geopolitics"],
    trend: "declining",
  },
  {
    id: "r7",
    name: "Ivan Petrov",
    outlet: "РИА Новости",
    country: "Russia",
    flag: "🇷🇺",
    neutralityScore: 31,
    biasDirection: "right",
    articleCount: 3102,
    topics: ["Geopolitics", "Military", "NATO"],
    trend: "declining",
  },
  {
    id: "r8",
    name: "Priya Sharma",
    outlet: "The Hindu",
    country: "India",
    flag: "🇮🇳",
    neutralityScore: 82,
    biasDirection: "neutral",
    articleCount: 729,
    topics: ["Energy", "Economy", "Climate"],
    trend: "improving",
  },
];

export const mockSignals: InvestmentSignal[] = [
  {
    id: "s1",
    asset: "Emerging Market Solar ETF",
    assetType: "stock",
    ticker: "EMSL",
    signal: "strong_buy",
    confidence: 87,
    priceTarget: 94.5,
    currentPrice: 71.3,
    changePercent: 2.4,
    reasoning: "Global South Cluster C3 (India, Brazil, Senegal, Indonesia) shows unanimous positive sentiment on renewable energy investment. Exclusive narrative gap vs. Western media creates asymmetric information opportunity.",
    relatedClusters: ["c3"],
    timeframe: "3-6 months",
    risk: "medium",
  },
  {
    id: "s2",
    asset: "Semiconductor Index",
    assetType: "stock",
    ticker: "SOX",
    signal: "buy",
    confidence: 72,
    priceTarget: 5840,
    currentPrice: 4921,
    changePercent: 1.8,
    reasoning: "Korean and Taiwanese sources (high neutrality scores) indicate chip shortage easing in Q3. Western media lagging on this narrative (divergence score: 74), creating a time-arbitrage opportunity.",
    relatedClusters: ["c2"],
    timeframe: "2-4 months",
    risk: "medium",
  },
  {
    id: "s3",
    asset: "Bitcoin",
    assetType: "crypto",
    ticker: "BTC",
    signal: "hold",
    confidence: 58,
    priceTarget: 72000,
    currentPrice: 68450,
    changePercent: -0.9,
    reasoning: "Mixed signals: Fed rate cut expectations (Cluster C1, positive) versus geopolitical uncertainty (Cluster C4, high divergence). Waiting for clearer directional consensus before upgrading signal.",
    relatedClusters: ["c1", "c4"],
    timeframe: "1-2 months",
    risk: "high",
  },
  {
    id: "s4",
    asset: "Gold Futures",
    assetType: "commodity",
    ticker: "GC",
    signal: "buy",
    confidence: 81,
    priceTarget: 2650,
    currentPrice: 2412,
    changePercent: 0.7,
    reasoning: "Geopolitical cluster C4 shows 96% divergence score — historically a leading indicator for gold demand spikes. Russian, Western, and Middle Eastern narratives are at maximum divergence levels.",
    relatedClusters: ["c4"],
    timeframe: "1-3 months",
    risk: "low",
  },
  {
    id: "s5",
    asset: "Agricultural Commodities",
    assetType: "commodity",
    ticker: "DBA",
    signal: "strong_buy",
    confidence: 83,
    priceTarget: 31.8,
    currentPrice: 22.4,
    changePercent: -0.3,
    reasoning: "Climate cluster C5 shows high consensus (divergence: 8) with alarming reports from France, Argentina, Australia. Southern Hemisphere crop yield warnings not yet priced into futures markets.",
    relatedClusters: ["c5"],
    timeframe: "6-12 months",
    risk: "medium",
  },
  {
    id: "s6",
    asset: "EUR/USD",
    assetType: "forex",
    ticker: "EURUSD",
    signal: "buy",
    confidence: 67,
    priceTarget: 1.12,
    currentPrice: 1.085,
    changePercent: 0.3,
    reasoning: "German and EU media (high neutrality scores) expressing strong optimism on Fed pivot benefiting European exports. Positive sentiment cluster (C1) with 18% divergence suggests broad agreement.",
    relatedClusters: ["c1"],
    timeframe: "2-3 months",
    risk: "low",
  },
];

export const mockTickers: MarketTicker[] = [
  { symbol: "SPX", name: "S&P 500", price: 5234.18, change: 28.4, changePercent: 0.54, type: "index" },
  { symbol: "NDX", name: "NASDAQ 100", price: 18442.5, change: 124.3, changePercent: 0.68, type: "index" },
  { symbol: "DAX", name: "DAX 40", price: 18721.3, change: -45.2, changePercent: -0.24, type: "index" },
  { symbol: "N225", name: "Nikkei 225", price: 38921.4, change: 312.1, changePercent: 0.81, type: "index" },
  { symbol: "BTC", name: "Bitcoin", price: 68450, change: -621, changePercent: -0.9, type: "crypto" },
  { symbol: "ETH", name: "Ethereum", price: 3842.1, change: 87.3, changePercent: 2.32, type: "crypto" },
  { symbol: "GC", name: "Gold", price: 2412.4, change: 16.8, changePercent: 0.7, type: "commodity" },
  { symbol: "CL", name: "WTI Crude", price: 79.34, change: -1.24, changePercent: -1.54, type: "commodity" },
  { symbol: "EURUSD", name: "EUR/USD", price: 1.0852, change: 0.0032, changePercent: 0.3, type: "forex" },
  { symbol: "USDJPY", name: "USD/JPY", price: 151.42, change: -0.84, changePercent: -0.55, type: "forex" },
  { symbol: "NVDA", name: "NVIDIA", price: 892.5, change: 21.4, changePercent: 2.46, type: "stock" },
  { symbol: "TSM", name: "TSMC", price: 147.8, change: 3.2, changePercent: 2.21, type: "stock" },
];

export const sentimentHistory = [
  { time: "08:00", positive: 42, negative: 28, neutral: 30 },
  { time: "09:00", positive: 38, negative: 32, neutral: 30 },
  { time: "10:00", positive: 45, negative: 25, neutral: 30 },
  { time: "11:00", positive: 40, negative: 35, neutral: 25 },
  { time: "12:00", positive: 35, negative: 40, neutral: 25 },
  { time: "13:00", positive: 30, negative: 45, neutral: 25 },
  { time: "14:00", positive: 38, negative: 38, neutral: 24 },
  { time: "15:00", positive: 44, negative: 30, neutral: 26 },
  { time: "16:00", positive: 48, negative: 26, neutral: 26 },
];
