import {
  NewsArticle,
  NarrativeCluster,
  Journalist,
  InvestmentSignal,
  AnalysisResult,
} from "./types";

const now = new Date().toISOString();
const hoursAgo = (h: number) =>
  new Date(Date.now() - h * 3600000).toISOString();

export const MOCK_ARTICLES: NewsArticle[] = [
  {
    id: "a1",
    title: "Federal Reserve Signals Potential Rate Cut Amid Global Slowdown",
    description: "The Fed hints at easing monetary policy as economic indicators soften across major economies.",
    content: "Federal Reserve officials indicated they may consider cutting interest rates...",
    url: "#",
    source: "Washington Post",
    country: "United States",
    countryCode: "us",
    language: "en",
    journalist: "Sarah Mitchell",
    publishedAt: hoursAgo(1),
    sentiment: 0.2,
    clusterId: "c1",
  },
  {
    id: "a2",
    title: "ECB Follows Dovish Tone as Eurozone Growth Stalls",
    description: "European Central Bank echoes Fed sentiment with potential rate adjustments.",
    content: "The European Central Bank signaled openness to monetary easing...",
    url: "#",
    source: "Der Spiegel",
    country: "Germany",
    countryCode: "de",
    language: "de",
    journalist: "Klaus Weber",
    publishedAt: hoursAgo(2),
    sentiment: -0.1,
    clusterId: "c1",
  },
  {
    id: "a3",
    title: "Bank of Japan Maintains Ultra-Loose Policy Despite Yen Weakness",
    description: "BOJ stands firm on its monetary stance even as the yen hits new lows.",
    content: "The Bank of Japan reiterated its commitment to accommodative monetary policy...",
    url: "#",
    source: "Nikkei",
    country: "Japan",
    countryCode: "jp",
    language: "ja",
    journalist: "Yuki Tanaka",
    publishedAt: hoursAgo(3),
    sentiment: -0.3,
    clusterId: "c1",
  },
  {
    id: "a4",
    title: "BRICS Nations Push for Alternative Payment System at Summit",
    description: "Emerging economies accelerate plans to reduce dollar dependency.",
    content: "At the latest BRICS summit, member nations announced concrete steps...",
    url: "#",
    source: "The Hindu",
    country: "India",
    countryCode: "in",
    language: "hi",
    journalist: "Priya Sharma",
    publishedAt: hoursAgo(1),
    sentiment: 0.5,
    clusterId: "c2",
  },
  {
    id: "a5",
    title: "South Africa Backs BRICS Currency Initiative",
    description: "South African delegation expresses strong support for new payment framework.",
    content: "South Africa's finance minister praised the new payment initiative...",
    url: "#",
    source: "News24",
    country: "South Africa",
    countryCode: "za",
    language: "en",
    journalist: "Thabo Mokoena",
    publishedAt: hoursAgo(2),
    sentiment: 0.6,
    clusterId: "c2",
  },
  {
    id: "a6",
    title: "Brazil Announces Trade Deal Bypassing US Dollar",
    description: "Brazil and China agree to conduct bilateral trade in local currencies.",
    content: "In a landmark agreement, Brazil and China will now settle trade...",
    url: "#",
    source: "Folha de S.Paulo",
    country: "Brazil",
    countryCode: "br",
    language: "pt",
    journalist: "Carlos Oliveira",
    publishedAt: hoursAgo(4),
    sentiment: 0.4,
    clusterId: "c2",
  },
  {
    id: "a7",
    title: "Lithium Shortage Threatens Global EV Transition",
    description: "Chile and Peru report declining output as demand surges.",
    content: "Chile's lithium production has dropped 15% due to water restrictions...",
    url: "#",
    source: "El Mercurio",
    country: "Chile",
    countryCode: "cl",
    language: "es",
    journalist: "Maria Rodriguez",
    publishedAt: hoursAgo(2),
    sentiment: -0.5,
    clusterId: "c3",
  },
  {
    id: "a8",
    title: "Peru Mining Protests Disrupt Copper Supply Chain",
    description: "Community protests halt operations at major copper mine.",
    content: "Protests near the Las Bambas copper mine have forced a temporary shutdown...",
    url: "#",
    source: "El Comercio",
    country: "Peru",
    countryCode: "pe",
    language: "es",
    journalist: "Jorge Vasquez",
    publishedAt: hoursAgo(3),
    sentiment: -0.6,
    clusterId: "c3",
  },
  {
    id: "a9",
    title: "China's Tech Giants Report Record AI Revenue Growth",
    description: "Alibaba, Tencent, and Baidu see unprecedented demand for AI services.",
    content: "China's major technology companies posted record quarterly results...",
    url: "#",
    source: "Global Times",
    country: "China",
    countryCode: "cn",
    language: "zh",
    journalist: "Wei Chen",
    publishedAt: hoursAgo(1),
    sentiment: 0.7,
    clusterId: "c4",
  },
  {
    id: "a10",
    title: "US-China Tech Competition Intensifies with New Chip Export Controls",
    description: "Washington expands semiconductor restrictions targeting Chinese AI firms.",
    content: "The Biden administration announced expanded export controls...",
    url: "#",
    source: "CNN",
    country: "United States",
    countryCode: "us",
    language: "en",
    journalist: "David Park",
    publishedAt: hoursAgo(2),
    sentiment: -0.4,
    clusterId: "c4",
  },
  {
    id: "a11",
    title: "Ukraine Reports Gains in Eastern Counteroffensive",
    description: "Ukrainian forces advance along key frontlines near Donetsk.",
    content: "The Ukrainian military command reported significant advances...",
    url: "#",
    source: "Kyiv Independent",
    country: "Ukraine",
    countryCode: "ua",
    language: "uk",
    journalist: "Olena Kovalenko",
    publishedAt: hoursAgo(1),
    sentiment: 0.3,
    clusterId: "c5",
  },
  {
    id: "a12",
    title: "Russia Claims Strategic Positions Held Despite Ukrainian Push",
    description: "Russian MoD denies significant territorial losses in Donetsk region.",
    content: "The Russian Ministry of Defense stated that all strategic positions...",
    url: "#",
    source: "TASS",
    country: "Russia",
    countryCode: "ru",
    language: "ru",
    journalist: "Dmitry Ivanov",
    publishedAt: hoursAgo(1),
    sentiment: 0.1,
    clusterId: "c5",
  },
  {
    id: "a13",
    title: "Indonesian Nickel Exports Surge as EV Battery Demand Grows",
    description: "Indonesia capitalizes on its nickel reserves for the electric vehicle market.",
    content: "Indonesia's nickel exports have increased 40% year-over-year...",
    url: "#",
    source: "Jakarta Post",
    country: "Indonesia",
    countryCode: "id",
    language: "id",
    journalist: "Adi Pratama",
    publishedAt: hoursAgo(5),
    sentiment: 0.5,
    clusterId: "c3",
  },
  {
    id: "a14",
    title: "Nigerian Tech Startups Attract Record Venture Capital",
    description: "Africa's largest economy sees a fintech boom amid banking reforms.",
    content: "Nigerian fintech startups raised over $2 billion in the first half...",
    url: "#",
    source: "Punch",
    country: "Nigeria",
    countryCode: "ng",
    language: "en",
    journalist: "Amara Okafor",
    publishedAt: hoursAgo(6),
    sentiment: 0.6,
  },
  {
    id: "a15",
    title: "Saudi Arabia Announces Massive Renewable Energy Investment",
    description: "Kingdom pledges $100B for solar and green hydrogen projects.",
    content: "Saudi Arabia unveiled an ambitious plan to diversify its energy portfolio...",
    url: "#",
    source: "Arab News",
    country: "Saudi Arabia",
    countryCode: "sa",
    language: "ar",
    journalist: "Ahmed Al-Rashid",
    publishedAt: hoursAgo(4),
    sentiment: 0.7,
  },
];

export const MOCK_CLUSTERS: NarrativeCluster[] = [
  {
    id: "c1",
    label: "Global Monetary Policy Shift",
    summary:
      "Central banks worldwide are pivoting toward dovish monetary policy. The Fed, ECB, and other major central banks signal potential rate cuts as global growth slows. Japan remains the outlier with ultra-loose policy.",
    countries: ["us", "de", "jp", "gb", "fr"],
    articles: MOCK_ARTICLES.filter((a) => a.clusterId === "c1"),
    sentimentScore: -0.1,
    keyTopics: ["Interest Rates", "Central Banks", "Monetary Policy", "Recession Risk"],
    articleCount: 3,
  },
  {
    id: "c2",
    label: "BRICS De-Dollarization Push",
    summary:
      "BRICS nations are accelerating efforts to create alternative payment systems and reduce dependency on the US dollar. India, South Africa, and Brazil lead concrete initiatives.",
    countries: ["in", "za", "br", "cn", "ru"],
    articles: MOCK_ARTICLES.filter((a) => a.clusterId === "c2"),
    sentimentScore: 0.5,
    keyTopics: ["BRICS", "Currency", "De-dollarization", "Trade"],
    articleCount: 3,
  },
  {
    id: "c3",
    label: "Critical Mineral Supply Crisis",
    summary:
      "South American lithium and copper production faces disruptions from environmental regulations and community protests. Indonesia emerges as alternative supply for nickel. Major implications for EV transition.",
    countries: ["cl", "pe", "id", "au"],
    articles: MOCK_ARTICLES.filter((a) => a.clusterId === "c3"),
    sentimentScore: -0.4,
    keyTopics: ["Lithium", "Copper", "Mining", "EV Supply Chain"],
    articleCount: 3,
  },
  {
    id: "c4",
    label: "US-China AI & Tech Race",
    summary:
      "Contrasting narratives emerge: China reports record AI revenue growth while the US expands tech export controls. The AI race is reshaping global tech supply chains.",
    countries: ["cn", "us", "kr", "jp"],
    articles: MOCK_ARTICLES.filter((a) => a.clusterId === "c4"),
    sentimentScore: 0.1,
    keyTopics: ["AI", "Semiconductors", "Export Controls", "Tech Competition"],
    articleCount: 2,
  },
  {
    id: "c5",
    label: "Ukraine Conflict: Competing Narratives",
    summary:
      "Starkly opposing narratives from Ukrainian and Russian sources regarding the eastern front. Ukrainian media reports gains; Russian media denies losses. Western and Eastern coverage diverges sharply.",
    countries: ["ua", "ru", "gb", "us", "de"],
    articles: MOCK_ARTICLES.filter((a) => a.clusterId === "c5"),
    sentimentScore: -0.2,
    keyTopics: ["Ukraine", "Russia", "Counteroffensive", "Conflict"],
    articleCount: 2,
  },
];

export const MOCK_JOURNALISTS: Journalist[] = [
  {
    id: "j1",
    name: "Sarah Mitchell",
    outlet: "Washington Post",
    country: "United States",
    countryCode: "us",
    neutralityScore: 72,
    articleCount: 342,
    biasHistory: [
      { date: "2025-10", score: 68 },
      { date: "2025-11", score: 70 },
      { date: "2025-12", score: 71 },
      { date: "2026-01", score: 73 },
      { date: "2026-02", score: 72 },
      { date: "2026-03", score: 72 },
    ],
    recentArticles: ["a1"],
  },
  {
    id: "j2",
    name: "Klaus Weber",
    outlet: "Der Spiegel",
    country: "Germany",
    countryCode: "de",
    neutralityScore: 81,
    articleCount: 215,
    biasHistory: [
      { date: "2025-10", score: 78 },
      { date: "2025-11", score: 79 },
      { date: "2025-12", score: 80 },
      { date: "2026-01", score: 81 },
      { date: "2026-02", score: 82 },
      { date: "2026-03", score: 81 },
    ],
    recentArticles: ["a2"],
  },
  {
    id: "j3",
    name: "Priya Sharma",
    outlet: "The Hindu",
    country: "India",
    countryCode: "in",
    neutralityScore: 76,
    articleCount: 189,
    biasHistory: [
      { date: "2025-10", score: 74 },
      { date: "2025-11", score: 75 },
      { date: "2025-12", score: 76 },
      { date: "2026-01", score: 77 },
      { date: "2026-02", score: 76 },
      { date: "2026-03", score: 76 },
    ],
    recentArticles: ["a4"],
  },
  {
    id: "j4",
    name: "Wei Chen",
    outlet: "Global Times",
    country: "China",
    countryCode: "cn",
    neutralityScore: 38,
    articleCount: 456,
    biasHistory: [
      { date: "2025-10", score: 35 },
      { date: "2025-11", score: 36 },
      { date: "2025-12", score: 37 },
      { date: "2026-01", score: 38 },
      { date: "2026-02", score: 39 },
      { date: "2026-03", score: 38 },
    ],
    recentArticles: ["a9"],
  },
  {
    id: "j5",
    name: "Dmitry Ivanov",
    outlet: "TASS",
    country: "Russia",
    countryCode: "ru",
    neutralityScore: 25,
    articleCount: 523,
    biasHistory: [
      { date: "2025-10", score: 28 },
      { date: "2025-11", score: 26 },
      { date: "2025-12", score: 25 },
      { date: "2026-01", score: 24 },
      { date: "2026-02", score: 25 },
      { date: "2026-03", score: 25 },
    ],
    recentArticles: ["a12"],
  },
  {
    id: "j6",
    name: "Olena Kovalenko",
    outlet: "Kyiv Independent",
    country: "Ukraine",
    countryCode: "ua",
    neutralityScore: 55,
    articleCount: 278,
    biasHistory: [
      { date: "2025-10", score: 52 },
      { date: "2025-11", score: 53 },
      { date: "2025-12", score: 54 },
      { date: "2026-01", score: 55 },
      { date: "2026-02", score: 56 },
      { date: "2026-03", score: 55 },
    ],
    recentArticles: ["a11"],
  },
  {
    id: "j7",
    name: "Yuki Tanaka",
    outlet: "Nikkei",
    country: "Japan",
    countryCode: "jp",
    neutralityScore: 85,
    articleCount: 167,
    biasHistory: [
      { date: "2025-10", score: 83 },
      { date: "2025-11", score: 84 },
      { date: "2025-12", score: 84 },
      { date: "2026-01", score: 85 },
      { date: "2026-02", score: 85 },
      { date: "2026-03", score: 85 },
    ],
    recentArticles: ["a3"],
  },
  {
    id: "j8",
    name: "Carlos Oliveira",
    outlet: "Folha de S.Paulo",
    country: "Brazil",
    countryCode: "br",
    neutralityScore: 69,
    articleCount: 201,
    biasHistory: [
      { date: "2025-10", score: 66 },
      { date: "2025-11", score: 67 },
      { date: "2025-12", score: 68 },
      { date: "2026-01", score: 69 },
      { date: "2026-02", score: 69 },
      { date: "2026-03", score: 69 },
    ],
    recentArticles: ["a6"],
  },
];

export const MOCK_SIGNALS: InvestmentSignal[] = [
  {
    id: "s1",
    asset: "Gold (XAU)",
    assetType: "commodity",
    direction: "buy",
    confidence: 0.87,
    reasoning:
      "BRICS de-dollarization push combined with global monetary easing creates strong tailwind for gold. Asymmetric information from Indian and South African sources suggests accelerated timeline.",
    relatedClusters: ["c1", "c2"],
    timestamp: hoursAgo(0.5),
    priceChange: 2.3,
  },
  {
    id: "s2",
    asset: "Albemarle (ALB)",
    assetType: "stock",
    direction: "sell",
    confidence: 0.78,
    reasoning:
      "Chilean and Peruvian local sources report worsening production conditions not yet reflected in Western coverage. Supply disruptions will pressure lithium producers.",
    relatedClusters: ["c3"],
    timestamp: hoursAgo(1),
    priceChange: -4.1,
  },
  {
    id: "s3",
    asset: "Bitcoin (BTC)",
    assetType: "crypto",
    direction: "buy",
    confidence: 0.72,
    reasoning:
      "Global monetary easing + de-dollarization narrative creates favorable macro backdrop. Emerging market adoption accelerating per local sources.",
    relatedClusters: ["c1", "c2"],
    timestamp: hoursAgo(2),
    priceChange: 5.7,
  },
  {
    id: "s4",
    asset: "NVIDIA (NVDA)",
    assetType: "stock",
    direction: "hold",
    confidence: 0.65,
    reasoning:
      "Chinese AI revenue growth is bullish, but expanded US export controls create uncertainty. Competing signals from Chinese and US sources suggest wait-and-see.",
    relatedClusters: ["c4"],
    timestamp: hoursAgo(3),
    priceChange: 0.8,
  },
  {
    id: "s5",
    asset: "Copper Futures",
    assetType: "commodity",
    direction: "buy",
    confidence: 0.82,
    reasoning:
      "Peru supply disruptions from local protests are underreported in global media. Supply squeeze incoming while demand remains robust for green transition.",
    relatedClusters: ["c3"],
    timestamp: hoursAgo(1.5),
    priceChange: 3.2,
  },
];

export const MOCK_ANALYSIS: AnalysisResult = {
  clusters: MOCK_CLUSTERS,
  journalists: MOCK_JOURNALISTS,
  signals: MOCK_SIGNALS,
  globalSentiment: 0.12,
  timestamp: now,
};
